---
steps:

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args: ["-c", "[[ '$_KEY' == $$KEY ]] && (echo 'pass';exit 0) || (echo 'fail';exit 1)"]
    secretEnv: ['KEY']

  - name: us-central1-docker.pkg.dev/gcp-expert-sandbox-allen/demo/gce-backup:v1
    entrypoint: /bin/bash
    args: ["-x", "$_BACKUP_SCRIPT"]

availableSecrets:
  secretManager:
  - versionName: projects/$_SECRET_PROJECT_ID/secrets/$_SECRET_NAME/versions/$_SECRET_VERSION
    env: 'KEY'

options:
  env:
  - TZ=$_TIMEZONE
  - instances=$_INSTANCES
  - project=$_PROJECT_ID
  - location=$_LOCATION
  - retainDays=$_RETAIN_DAYS

substitutions:
  _TIMEZONE: Asia/Taipei
  _PROJECT_ID: gcp-expert-sandbox-allen
  #_PROJECT_ID: $PROJECT_ID
  _INSTANCES: docker:us-central1-a win2016:us-central1-a
  _LOCATION: us-central1
  _RETAIN_DAYS: "7"
  _BACKUP_SCRIPT: /gce-backup.sh
  _SECRET_PROJECT_ID: gcp-expert-sandbox-allen
  _SECRET_NAME: gcp-expert-sandbox-allen
  _SECRET_VERSION: latest
  _KEY: password


timeout: 6000s